server:
  servlet:
    context-path: /mail-service
spring:
  application:
    name: bloggios-mail-service
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.bloggios.email
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE}?currentSchema=mail-service
    hikari:
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASSWORD}
      maximum-pool-size: ${POSTGRES_POOL_SIZE:100}
      minimum-idle: ${POSTGRES_IDLE:7}
      leak-detection-threshold: 120000
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
mail-service:
  kafka:
    group-id: ${ACTIVE_PROFILE:local}.mail-service
    consumer:
      topics:
        registration-otp: ${ACTIVE_PROFILE:local}.auth-provider.registration-otp
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        exclude: prometheus
application:
  version: @version@
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    allow-redirects: true
    service-url:
      defaultZone: ${EUREKA_URL}
    enabled: false
mail-configuration:
  google-mail: # Please add your gmail details below
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}