server:
  servlet:
    context-path: /mail-service
spring:
  application:
    name: bloggios-mail-service
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.bloggios.email
mail-service:
  kafka:
    group-id: ${ACTIVE_PROFILE:local}.mail-service
    consumer:
      topics:
        registration-otp: ${ACTIVE_PROFILE:local}.auth-provider.registration-otp
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        exclude: prometheus
application:
  version: @version@
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    allow-redirects: true
    service-url:
      defaultZone: ${EUREKA_URL}
    enabled: false